# Generated by Django 5.0.3 on 2024-03-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="img_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
