# Generated by Django 5.0.3 on 2024-03-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_rename_img_url_chat_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="image_contnet",
            field=models.ImageField(
                blank=True, null=True, upload_to="generated_images/"
            ),
        ),
    ]
