# Generated by Django 5.0.3 on 2024-03-24 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0004_chat_image_contnet"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chat",
            old_name="image_contnet",
            new_name="image_content",
        ),
    ]
