# Generated by Django 5.0.3 on 2024-03-25 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0005_rename_image_contnet_chat_image_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="image_content",
        ),
    ]
