# Generated by Django 5.0.3 on 2024-03-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0007_chat_session_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="session_id",
        ),
    ]
